server:
  port: 8080
  servlet:
    context-path: /app
spring:
  datasource:
    url: jdbc:h2:mem:appdb;MODE=PostgreSQL
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
#      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect:
          PostgreSQLDialect

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE